version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://admin.ant.ae/api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://admin.ant.ae/api
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /path/to/your/fullchain.pem:/etc/ssl/certs/fullchain.pem  # Update with actual path
      - /path/to/your/privkey.pem:/etc/ssl/private/privkey.pem    # Update with actual path
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
