# Generated by Django 5.0 on 2024-12-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['day'], 'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together={('service_voucher', 'day')},
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('activity_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('TOUR', 'Tour/Activity'), ('CHECKIN', 'Hotel Check-in'), ('CHECKOUT', 'Hotel Check-out'), ('MEAL', 'Meal'), ('FREE', 'Free Time'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operations.itinerary')),
            ],
            options={
                'verbose_name_plural': 'Itinerary Activities',
                'ordering': ['time'],
            },
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='time',
        ),
    ]
